---
- name: Configuração Inicial do Servidor (Fase 2)
  hosts: linux_servers
  become: yes  # Isto diz ao Ansible para usar o comando 'sudo' (Root)

  tasks:
    - name: Atualizar os repositorios (apt update)
      apt:
        update_cache: yes

    - name: Garantir que as ferramentas base estao instaladas
      apt:
        name:
          - curl
          - wget
          - htop
          - qemu-guest-agent
        state: present