name: Homelab IaC Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Aprovisionar Infraestrutura
    runs-on: self-hosted

    steps:
      - name: 1. Fazer o Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Injetar Segredos do Cofre
        run: |
          echo 'vm_password = "${{ secrets.VM_PASSWORD }}"' > secrets.auto.tfvars
          echo 'proxmox_api_token = "${{ secrets.PROXMOX_TOKEN }}"' >> secrets.auto.tfvars
          echo 'domain_password: "${{ secrets.AD_PASSWORD }}"' > ansible_secrets.yml

      - name: 3. Terraform (Init e Apply)
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: 4. Ansible (Configuração e AD Join)
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          echo "A aguardar 60 segundos para as VMs iniciarem o serviço SSH..."
          sleep 60
          ansible-playbook -i hosts.ini ad_join.yml